(ns hashgraph.main-analysis)

(def var-usages
[{:from-ns "hashgraph.main",
  :from-var "parents",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "parents",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "parents",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "parents",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-parent?",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "other-parent?",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "parent?",
  :to-ns "hashgraph.main",
  :to-var "self-parent?"}
 {:from-ns "hashgraph.main",
  :from-var "parent?",
  :to-ns "hashgraph.main",
  :to-var "other-parent?"}
 {:from-ns "hashgraph.main",
  :from-var "ancestor?",
  :to-ns "hashgraph.main",
  :to-var "parent?"}
 {:from-ns "hashgraph.main",
  :from-var "ancestor?",
  :to-ns "hashgraph.main",
  :to-var "ancestor?"}
 {:from-ns "hashgraph.main",
  :from-var "ancestor?",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "self-ancestor?",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-ancestor?",
  :to-ns "hashgraph.main",
  :to-var "self-parent?"}
 {:from-ns "hashgraph.main",
  :from-var "self-ancestor?",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-ancestor?",
  :to-ns "hashgraph.main",
  :to-var "self-ancestor?"}
 {:from-ns "hashgraph.main",
  :from-var "index",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "index",
  :to-ns "hashgraph.main",
  :to-var "index"}
 {:from-ns "hashgraph.main",
  :from-var "index",
  :to-ns "hashgraph.main",
  :to-var "index"}
 {:from-ns "hashgraph.main",
  :from-var "index",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "see?",
  :to-ns "hashgraph.main",
  :to-var "ancestor?"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "seen-by"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "seen-by",
  :to-ns "hashgraph.main",
  :to-var "seen-by"}
 {:from-ns "hashgraph.main",
  :from-var "see-many-see?",
  :to-ns "hashgraph.main",
  :to-var "seen-by"}
 {:from-ns "hashgraph.main",
  :from-var "see-many-see?",
  :to-ns "hashgraph.members",
  :to-var "many"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "merge-rws"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "round->witnesses->seen-by"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.members",
  :to-var "many"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.members",
  :to-var "many"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round->witnesses->seen-by",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "round",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "round",
  :to-ns "hashgraph.main",
  :to-var "round->witnesses->seen-by"}
 {:from-ns "hashgraph.main",
  :from-var "witness?",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "witness?",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "witness?",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "witness?",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-diff",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-diff",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "voting-round?",
  :to-ns "hashgraph.main",
  :to-var "voting-round?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-round?",
  :to-ns "hashgraph.main",
  :to-var "rounds-diff"}
 {:from-ns "hashgraph.main",
  :from-var "voting-round?",
  :to-ns "hashgraph.main",
  :to-var "d"}
 {:from-ns "hashgraph.main",
  :from-var "voting-coin-flip-round?",
  :to-ns "hashgraph.main",
  :to-var "voting-coin-flip-round?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-coin-flip-round?",
  :to-ns "hashgraph.main",
  :to-var "voting-round?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-coin-flip-round?",
  :to-ns "hashgraph.main",
  :to-var "rounds-diff"}
 {:from-ns "hashgraph.main",
  :from-var "voting-coin-flip-round?",
  :to-ns "hashgraph.main",
  :to-var "c"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "witness?"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "self-witness",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "witness?"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "round-witnesses",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "same-round-events"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "same-round-events"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "same-round-events",
  :to-ns "hashgraph.main",
  :to-var "same-round-events"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "parents"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "same-round-events"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "round-whether-received-events",
  :to-ns "hashgraph.main",
  :to-var "round-whether-received-events"}
 {:from-ns "hashgraph.main",
  :from-var "round-received-events",
  :to-ns "hashgraph.main",
  :to-var "round-whether-received-events"}
 {:from-ns "hashgraph.main",
  :from-var "round-not-received-events",
  :to-ns "hashgraph.main",
  :to-var "round-whether-received-events"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "self-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "learned-member-learned-evt"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "other-parent"}
 {:from-ns "hashgraph.main",
  :from-var "learned-member-learned-evt",
  :to-ns "hashgraph.main",
  :to-var "learned-member-learned-evt"}
 {:from-ns "hashgraph.main",
  :from-var "received-time",
  :to-ns "hashgraph.main",
  :to-var "learned-member-learned-evt"}
 {:from-ns "hashgraph.main",
  :from-var "received-time",
  :to-ns "hashgraph.main",
  :to-var "median"}
 {:from-ns "hashgraph.main",
  :from-var "order-events",
  :to-ns "hashgraph.main",
  :to-var "received-time"}
 {:from-ns "hashgraph.main",
  :from-var "order-events",
  :to-ns "hashgraph.main",
  :to-var "received-time"}
 {:from-ns "hashgraph.main",
  :from-var "vote-see?",
  :to-ns "hashgraph.main",
  :to-var "rounds-diff"}
 {:from-ns "hashgraph.main",
  :from-var "vote-see",
  :to-ns "hashgraph.main",
  :to-var "see?"}
 {:from-ns "hashgraph.main",
  :from-var "vote-see",
  :to-ns "hashgraph.main",
  :to-var "make-vote"}
 {:from-ns "hashgraph.main",
  :from-var "vote-copy?",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "vote-copy?",
  :to-ns "hashgraph.main",
  :to-var "voting-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "vote-copy",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "vote-copy",
  :to-ns "hashgraph.main",
  :to-var "vote"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip?",
  :to-ns "hashgraph.main",
  :to-var "voting-coin-flip-round?"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip?",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-fract-true"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip?",
  :to-ns "hashgraph.main",
  :to-var "stake-many"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip?",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-fract-true"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip?",
  :to-ns "hashgraph.main",
  :to-var "stake-many"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip",
  :to-ns "hashgraph.main",
  :to-var "signature"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip",
  :to-ns "hashgraph.main",
  :to-var "middle-bit"}
 {:from-ns "hashgraph.main",
  :from-var "vote-coin-flip",
  :to-ns "hashgraph.main",
  :to-var "make-vote"}
 {:from-ns "hashgraph.main",
  :from-var "vote-for-majority",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-fract-true"}
 {:from-ns "hashgraph.main",
  :from-var "vote-for-majority",
  :to-ns "hashgraph.main",
  :to-var "make-vote"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-see?"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-see"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-copy?"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-copy"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-coin-flip?"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-coin-flip"}
 {:from-ns "hashgraph.main",
  :from-var "vote",
  :to-ns "hashgraph.main",
  :to-var "vote-for-majority"}
 {:from-ns "hashgraph.main",
  :from-var "votes",
  :to-ns "hashgraph.main",
  :to-var "vote"}
 {:from-ns "hashgraph.main",
  :from-var "votes",
  :to-ns "hashgraph.main",
  :to-var "see-many-see?"}
 {:from-ns "hashgraph.main",
  :from-var "votes",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "votes",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "votes-stake-true",
  :to-ns "hashgraph.main",
  :to-var "votes"}
 {:from-ns "hashgraph.main",
  :from-var "votes-stake-false",
  :to-ns "hashgraph.main",
  :to-var "votes"}
 {:from-ns "hashgraph.main",
  :from-var "votes-stake-fract-true",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-true"}
 {:from-ns "hashgraph.main",
  :from-var "votes-stake-fract-true",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-false"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "voting-round?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "voting-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "voting-coin-flip-round?"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-true"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "stake-many"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "votes-stake-false"}
 {:from-ns "hashgraph.main",
  :from-var "voting-concluded?",
  :to-ns "hashgraph.main",
  :to-var "stake-many"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "witness?"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "d"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "round-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "round-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "event+round->round-last-received-event"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "received-event->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "voting-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded?",
  :to-ns "hashgraph.main",
  :to-var "round-witnesses"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "witness?"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "rounds-concluded"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "round-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "rounds-concluded",
  :to-ns "hashgraph.main",
  :to-var "round"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded-witness",
  :to-ns "hashgraph.main",
  :to-var "round-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded-witness",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded-witness",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded-witness",
  :to-ns "hashgraph.main",
  :to-var "round-concluded-witness"}
 {:from-ns "hashgraph.main",
  :from-var "round-concluded-witness",
  :to-ns "hashgraph.main",
  :to-var "witness?"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "round-concluded?"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "self-witness"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "event+round->round-last-received-event"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "round-received-events"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "order-events"}
 {:from-ns "hashgraph.main",
  :from-var "event+round->round-last-received-event",
  :to-ns "hashgraph.main",
  :to-var "event+round->round-last-received-event"}
 {:from-ns "hashgraph.main",
  :from-var "last-received-event",
  :to-ns "hashgraph.main",
  :to-var "rounds-concluded"}
 {:from-ns "hashgraph.main",
  :from-var "last-received-event",
  :to-ns "hashgraph.main",
  :to-var "event+round->round-last-received-event"}
 {:from-ns "hashgraph.main",
  :from-var "stake-many",
  :to-ns "hashgraph.main",
  :to-var "total-stake"}
 {:from-ns "hashgraph.main",
  :from-var "initial-share-stake-log",
  :to-ns "hashgraph.main",
  :to-var "total-stake"}
 {:from-ns "hashgraph.main",
  :from-var "initial-share-stake-log",
  :to-ns "hashgraph.members",
  :to-var "initial-member-names"}
 {:from-ns "hashgraph.main",
  :from-var "initial-share-stake-log",
  :to-ns "hashgraph.members",
  :to-var "initial-member-names"}
 {:from-ns "hashgraph.main",
  :from-var "share-stake-log->member-stake-map",
  :to-ns "hashgraph.main",
  :to-var "share-stake-log->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "init-db",
  :to-ns "hashgraph.main",
  :to-var "initial-share-stake-log"}
 {:from-ns "hashgraph.main",
  :from-var "fns",
  :to-ns "hashgraph.main",
  :to-var "share-stake-log->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "init-db"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "fns"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "received-event->derived-db"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "received-event->derived-db"}
 {:from-ns "hashgraph.main",
  :from-var "event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "last-received-event"}
 {:from-ns "hashgraph.main",
  :from-var "event->derived-db",
  :to-ns "hashgraph.main",
  :to-var "received-event->derived-db"}
 {:from-ns "hashgraph.main",
  :from-var "event->member-stake-map",
  :to-ns "hashgraph.main",
  :to-var "event->derived-db"}
 {:from-ns "hashgraph.main",
  :from-var "event->member-stake-map",
  :to-ns "hashgraph.main",
  :to-var "share-stake-log->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->member-stake-map",
  :to-ns "hashgraph.main",
  :to-var "received-event->derived-db"}
 {:from-ns "hashgraph.main",
  :from-var "received-event->member-stake-map",
  :to-ns "hashgraph.main",
  :to-var "share-stake-log->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "event->member",
  :to-ns "hashgraph.main",
  :to-var "creator"}
 {:from-ns "hashgraph.main",
  :from-var "event->member",
  :to-ns "hashgraph.main",
  :to-var "event->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "event->member",
  :to-ns "hashgraph.members",
  :to-var "member-name->person"}
 {:from-ns "hashgraph.main",
  :from-var "event->stake",
  :to-ns "hashgraph.main",
  :to-var "event->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "event->most-weigted-member",
  :to-ns "hashgraph.main",
  :to-var "event->member-stake-map"}
 {:from-ns "hashgraph.main",
  :from-var "event->present-members",
  :to-ns "hashgraph.members",
  :to-var "member-name->person"}
 {:from-ns "hashgraph.main",
  :from-var "event->present-members",
  :to-ns "hashgraph.members",
  :to-var "member-name->person"}
 {:from-ns "hashgraph.main",
  :from-var "event->present-members",
  :to-ns "hashgraph.main",
  :to-var "event->member-stake-map"}]
)